/*****************************************************************
 * DO NOT MANUALLY EDIT THIS FILE!                               *
 *                                                               *
 * This file is auto-generated by 'yarn prepare'                 *
 *****************************************************************/

import { CourseConfirmCloseModalComponent } from './academy/instructor/dashboard-page/course-confirm-close-modal/course-confirm-close-modal.component';
import { CourseConfirmDeleteModalComponent } from './academy/instructor/dashboard-page/course-confirm-delete-modal/course-confirm-delete-modal.component';
import { CourseConfirmPublishModalComponent } from './academy/instructor/dashboard-page/course-confirm-publish-modal/course-confirm-publish-modal.component';
import { CourseConfirmUnpublishModalComponent } from './academy/instructor/dashboard-page/course-confirm-unpublish-modal/course-confirm-unpublish-modal.component';
import { ContestAwardModalComponent } from './contests/contest-award-modal/contest-award-modal.component';
import { ContestBuyModalComponent } from './contests/contest-buy-modal/contest-buy-modal.component';
import { ContestFilePreviewModalComponent } from './contests/contest-file-preview-modal/contest-file-preview-modal.component';
import { ContestInterestedFreelancersModalComponent } from './contests/contest-interested-freelancers-modal/contest-interested-freelancers-modal.component';
import { ContestMakeOfferModalComponent } from './contests/contest-make-offer-modal/contest-make-offer-modal.component';
import { ContestMultiAwardModalComponent } from './contests/contest-multi-award-modal/contest-multi-award-modal.component';
import { ContestPollsModalComponent } from './contests/contest-view/contest-details-tab/contest-polls/contest-polls-modal/contest-polls-modal.component';
import { QuickviewModalComponent } from './contests/contest-view/contest-entries-tab/entry-list/quickview-modal/quickview-modal.component';
import { CreateCollectionModalComponent } from './discover-collections/create-collection-modal/create-collection-modal.component';
import { DeleteCollectionModalComponent } from './discover-collections/delete-collection-modal/delete-collection-modal.component';
import { SaveToCollectionModalComponent } from './discover-collections/save-to-collection-modal/save-to-collection-modal.component';
import { DiscoverManageDeleteModalComponent } from './discover/discover-manage-portfolio-page/discover-manage-delete-modal/discover-manage-delete-modal.component';
import { DiscoverPublishCancelModalComponent } from './discover/publish/form/cancel-modal/discover-publish-cancel-modal.component';
import { FileAttachmentsModalComponent } from './file-attachments-modal/file-attachments-modal.component';
import { LinkedAccountsConfirmationModalComponent } from './freelancer-onboarding/freelancer-onboarding-linked-accounts/linked-accounts-confirmation-modal/linked-accounts-confirmation-modal.component';
import { FreelancerVerifiedLandingStatusModalComponent } from './freelancer-verified/freelancer-verified-landing/freelancer-verified-landing-status-modal/freelancer-verified-landing-status-modal.component';
import { GlobalfleetModalComponent } from './globalfleet/globalfleet-modal/globalfleet-modal.component';
import { GroupConfirmationModalComponent } from './groups/groups-common/group-confirmation-modal/group-confirmation-modal.component';
import { HireMeHourlyConfirmationModalComponent } from './hire-me/hire-me-hourly-confirmation-modal/hire-me-hourly-confirmation-modal.component';
import { HireMePaymentVerifyModalComponent } from './hire-me/hire-me-payment-verify-modal/hire-me-payment-verify-modal.component';
import { HireMeWebappModalComponent } from './hire-me/hire-me-webapp-modal/hire-me-webapp-modal.component';
import { ArrowOnboardingModalComponent } from './jobs/job-post/arrow/onboarding-modal/arrow-onboarding-modal.component';
import { ArrowLoginSignupModalComponent } from './login-signup/arrow-login-signup-modal/arrow-login-signup-modal.component';
import { LoginSignupModalComponent } from './login-signup/login-signup-modal/login-signup-modal.component';
import { ManageFilterModalComponent } from './manage/shared/manage-top-nav/manage-filter-modal/manage-filter-modal.component';
import { WorkProjectActionsModalComponent } from './manage/work/projects/work-project-actions/work-project-actions-modal/work-project-actions-modal.component';
import { MembershipPackageCtaModalComponent } from './membership/membership-package-card/membership-package-cta/membership-package-cta-modal/membership-package-cta-modal.component';
import { LoadingModalComponent } from './membership/trial/loading-modal/loading-modal.component';
import { PaymentVerificationNoticeModalComponent } from './membership/trial/payment-verification-notice-modal/payment-verification-notice-modal.component';
import { SubscriptionErrorModalComponent } from './membership/trial/subscription-error-modal/subscription-error-modal.component';
import { TrialSuccessModalComponent } from './membership/trial/trial-success-modal/trial-success-modal.component';
import { CallAlertModalComponent } from './messaging/messaging-chat/call-alert-modal/call-alert-modal.component';
import { FileViewerModalComponent } from './messaging/messaging-chat/file-viewer-modal/file-viewer-modal.component';
import { GroupchatManagementModalComponent } from './messaging/messaging-chat/groupchat-management-modal/groupchat-management-modal.component';
import { MessagingAttachmentModalComponent } from './messaging/messaging-chat/messaging-attachment-modal/messaging-attachment-modal.component';
import { PaymentsOverlayComponent } from './payments/common/payments-overlay/payments-overlay.component';
import { PaymentShareModalComponent } from './payments/payment-share-modal/payment-share-modal.component';
import { PaymentVerifyModalComponent } from './payments/payment-verify/payment-verify-modal/payment-verify-modal.component';
import { PaymentsModalComponent } from './payments/payments-deposit/payments-modal/payments-modal.component';
import { PortfolioItemAttachmentModalComponent } from './portfolio-item-page/attachment-modal/portfolio-item-attachment-modal.component';
import { AwardModalComponent } from './projects/award-modal/award-modal.component';
import { BidAwardRevokeModalComponent } from './projects/bid-award-revoke-modal/bid-award-revoke-modal.component';
import { CloseBiddingModalComponent } from './projects/close-bidding-modal/close-bidding-modal.component';
import { HourlyAwardModalComponent } from './projects/hourly-award-modal/hourly-award-modal.component';
import { InviteModalComponent } from './projects/invite-modal/invite-modal.component';
import { MarketingMobileNumberModalComponent } from './projects/marketing-mobile-number-modal/marketing-mobile-number-modal.component';
import { MilestoneCancelModalComponent } from './projects/milestone-cancel-modal/milestone-cancel-modal.component';
import { MilestoneCreateModalComponent } from './projects/milestone-create-modal/milestone-create-modal.component';
import { ProjectDeleteModalComponent } from './projects/project-delete-modal/project-delete-modal.component';
import { ProjectEndModalComponent } from './projects/project-end-modal/project-end-modal.component';
import { ProjectFileRenameModalComponent } from './projects/project-files/project-file-rename-modal/project-file-rename-modal.component';
import { ProjectFileShareModalComponent } from './projects/project-files/project-file-share-modal/project-file-share-modal.component';
import { ProjectFilesPreviewModalComponent } from './projects/project-files/project-files-preview-modal/project-files-preview-modal.component';
import { CloseProjectModalComponent } from './projects/project-view/close-project-modal/close-project-modal.component';
import { DeloitteAdditionalInfoLocationModalComponent } from './projects/project-view/project-view-details/deloitte-additional-info/deloitte-additional-info-location-modal/deloitte-additional-info-location-modal.component';
import { ProjectUpgradeModalComponent } from './projects/project-view/project-view-employer/project-upgrades/project-upgrade-modal/project-upgrade-modal.component';
import { ProjectFileFilterModalComponent } from './projects/project-view/project-view-files/project-file-filter-modal.compontent/project-file-filter-modal.component';
import { ProjectManagerSidebarModalComponent } from './projects/project-view/project-view-payments/employer-payments-area/sidebars/project-manager-sidebar/project-manager-sidebar-modal/project-manager-sidebar-modal.component';
import { DownloadDesktopModalComponent } from './projects/project-view/project-view-payments/freelancer-payments-area/download-desktop-modal/download-desktop-modal.component';
import { RejectProjectModalComponent } from './projects/project-view/project-view-payments/freelancer-payments-area/reject-project-modal/reject-project-modal.component';
import { MilestoneReleaseModalComponent } from './projects/project-view/project-view-payments/milestone-release-modal/milestone-release-modal.component';
import { ProjectEndBillingModalComponent } from './projects/project-view/project-view-payments/project-end-billing-modal/project-end-billing-modal.component';
import { BidMoreFiltersModalComponent } from './projects/project-view/project-view-proposals/bid-list-filtering-wrapper/bid-list-filters/bid-more-filters-modal/bid-more-filters-modal.component';
import { BidRetractModalComponent } from './projects/project-view/project-view-proposals/bid-list/bid-card-new/bid-retract-modal/bid-retract-modal.component';
import { EmployerNewRehireProjectModalComponent } from './projects/project-view/project-view-reviews/review-area/employer-new-rehire-project-modal/employer-new-rehire-project-modal.component';
import { ProjectCollaborationRevokeModalComponent } from './projects/project-view/project-view-share/project-collaboration-revoke-modal/project-collaboration-revoke-modal.component';
import { CreateMilestoneFromInvoiceModalComponent } from './projects/project-view/project-view-tracking/create-milestone-from-invoice-modal/create-milestone-from-invoice-modal.component';
import { DeleteTimeTrackingSessionModalComponent } from './projects/project-view/project-view-tracking/tracked-time-list-view/hourly-sessions-list/hourly-session-item/delete-time-tracking-session-modal/delete-time-tracking-session-modal.component';
import { PunchViewerModalComponent } from './projects/project-view/punch-viewer-modal/punch-viewer-modal.component';
import { UserPortfolioItemOverlayComponent } from './projects/project-view/user-profile-information/user-portfolio/user-portfolio-item-overlay/user-portfolio-item-overlay.component';
import { GiveGetModalComponent } from './referrals/give-get-modal/give-get-modal.component';
import { SearchFiltersModalComponent } from './search/search-filters-modal/search-filters-modal.component';
import { SkillsEditModalComponent } from './skills-edit-modal/skills-edit-modal.component';
import { TaskModalComponent } from './tasks/task-modal/task-modal.component';
import { TutorialModalComponent } from './tutorial/home/tutorial-modal/tutorial-modal.component';
import { SuggestedMilestonesModalComponent } from './user-profile/user-profile-award-project-sidebar/suggested-milestones-modal/suggested-milestones-modal.component';
import { ProfileVerificationsModalComponent } from './user-profile/user-profile-summary/user-profile-summary-verifications/profile-verifications-modal/profile-verifications-modal.component';
import { ViolationReportModalComponent } from './violation-report-modal/violation-report-modal.component';

export const allModalComponents = {
  CourseConfirmCloseModalComponent,
  CourseConfirmDeleteModalComponent,
  CourseConfirmPublishModalComponent,
  CourseConfirmUnpublishModalComponent,
  ContestAwardModalComponent,
  ContestBuyModalComponent,
  ContestFilePreviewModalComponent,
  ContestInterestedFreelancersModalComponent,
  ContestMakeOfferModalComponent,
  ContestMultiAwardModalComponent,
  ContestPollsModalComponent,
  QuickviewModalComponent,
  CreateCollectionModalComponent,
  DeleteCollectionModalComponent,
  SaveToCollectionModalComponent,
  DiscoverManageDeleteModalComponent,
  DiscoverPublishCancelModalComponent,
  FileAttachmentsModalComponent,
  LinkedAccountsConfirmationModalComponent,
  FreelancerVerifiedLandingStatusModalComponent,
  GlobalfleetModalComponent,
  GroupConfirmationModalComponent,
  HireMeHourlyConfirmationModalComponent,
  HireMePaymentVerifyModalComponent,
  HireMeWebappModalComponent,
  ArrowOnboardingModalComponent,
  ArrowLoginSignupModalComponent,
  LoginSignupModalComponent,
  ManageFilterModalComponent,
  WorkProjectActionsModalComponent,
  MembershipPackageCtaModalComponent,
  LoadingModalComponent,
  PaymentVerificationNoticeModalComponent,
  SubscriptionErrorModalComponent,
  TrialSuccessModalComponent,
  CallAlertModalComponent,
  FileViewerModalComponent,
  GroupchatManagementModalComponent,
  MessagingAttachmentModalComponent,
  PaymentsOverlayComponent,
  PaymentShareModalComponent,
  PaymentVerifyModalComponent,
  PaymentsModalComponent,
  PortfolioItemAttachmentModalComponent,
  AwardModalComponent,
  BidAwardRevokeModalComponent,
  CloseBiddingModalComponent,
  HourlyAwardModalComponent,
  InviteModalComponent,
  MarketingMobileNumberModalComponent,
  MilestoneCancelModalComponent,
  MilestoneCreateModalComponent,
  ProjectDeleteModalComponent,
  ProjectEndModalComponent,
  ProjectFileRenameModalComponent,
  ProjectFileShareModalComponent,
  ProjectFilesPreviewModalComponent,
  CloseProjectModalComponent,
  DeloitteAdditionalInfoLocationModalComponent,
  ProjectUpgradeModalComponent,
  ProjectFileFilterModalComponent,
  ProjectManagerSidebarModalComponent,
  DownloadDesktopModalComponent,
  RejectProjectModalComponent,
  MilestoneReleaseModalComponent,
  ProjectEndBillingModalComponent,
  BidMoreFiltersModalComponent,
  BidRetractModalComponent,
  EmployerNewRehireProjectModalComponent,
  ProjectCollaborationRevokeModalComponent,
  CreateMilestoneFromInvoiceModalComponent,
  DeleteTimeTrackingSessionModalComponent,
  PunchViewerModalComponent,
  UserPortfolioItemOverlayComponent,
  GiveGetModalComponent,
  SearchFiltersModalComponent,
  SkillsEditModalComponent,
  TaskModalComponent,
  TutorialModalComponent,
  SuggestedMilestonesModalComponent,
  ProfileVerificationsModalComponent,
  ViolationReportModalComponent,
};
