/*****************************************************************
 * DO NOT MANUALLY EDIT THIS FILE!                               *
 *                                                               *
 * This file is auto-generated by 'yarn prepare'                 *
 *****************************************************************/

import { CameraModalComponent } from './camera-modal/camera-modal.component';

export const allModalComponents = {
  CameraModalComponent,
};
